# Dockerfile.dev
FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    zip unzip && \
    docker-php-ext-install pdo pdo_mysql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# En desarrollo usarás volúmenes, por eso NO copiamos código aquí
